"""dms_enhancements

Revision ID: 1979b0b07d2a
Revises: 9ebef81043fb
Create Date: 2026-06-15 02:30:13.159671

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1979b0b07d2a'
down_revision: Union[str, None] = '9ebef81043fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('original_filename', sa.String(), nullable=True))
    op.add_column('documents', sa.Column('mime_type', sa.String(), nullable=True))
    op.add_column('documents', sa.Column('storage_path', sa.String(), nullable=True))
    
    # Manually added ENUM rename/update
    # The 'manager' label already exists in the enum, so we just update the rows.
    op.execute("UPDATE users SET role = 'manager' WHERE role = 'approver'")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'storage_path')
    op.drop_column('documents', 'mime_type')
    op.drop_column('documents', 'original_filename')
    
    # Manually added ENUM rename downgrade
    op.execute("UPDATE users SET role = 'approver' WHERE role = 'manager'")
    # ### end Alembic commands ###
