"""Add password_reset_tokens

Revision ID: 4001e7dee98e
Revises: b7d2e4f19c03
Create Date: 2026-06-15 03:31:51.101128

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4001e7dee98e'
down_revision: Union[str, None] = 'b7d2e4f19c03'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('password_reset_tokens',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.String(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_password_reset_tokens_token_hash'), 'password_reset_tokens', ['token_hash'], unique=True)
    op.create_index(op.f('ix_password_reset_tokens_user_id'), 'password_reset_tokens', ['user_id'], unique=False)
    # Dropping columns is disabled to prevent accidental data loss
    # op.drop_column('approval_workflows', 'previous_status')
    # op.drop_column('approval_workflows', 'user_role')
    # op.drop_column('audit_logs', 'user_role')
    # op.drop_column('audit_logs', 'comments')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audit_logs', sa.Column('comments', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('audit_logs', sa.Column('user_role', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('approval_workflows', sa.Column('user_role', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('approval_workflows', sa.Column('previous_status', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_password_reset_tokens_user_id'), table_name='password_reset_tokens')
    op.drop_index(op.f('ix_password_reset_tokens_token_hash'), table_name='password_reset_tokens')
    op.drop_table('password_reset_tokens')
    # ### end Alembic commands ###
