"""rbac_audit_logs

Revision ID: 8a4e15b309eb
Revises: 4001e7dee98e
Create Date: 2026-06-15 13:11:46.561440

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8a4e15b309eb'
down_revision: Union[str, None] = '4001e7dee98e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audit_logs', sa.Column('user_email', sa.String(), nullable=True))
    op.add_column('audit_logs', sa.Column('user_role', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('audit_logs', 'user_role')
    op.drop_column('audit_logs', 'user_email')
    # ### end Alembic commands ###
