"""feature_enhancement

Revision ID: 9ebef81043fb
Revises: 001_initial
Create Date: 2026-06-14 08:29:58.580654

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ebef81043fb'
down_revision: Union[str, None] = '001_initial'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('confidence_score', sa.Numeric(precision=5, scale=4), nullable=True))
    # ### end Alembic commands ###

    # Workaround for PostgreSQL ENUM transaction limit:
    # We will just commit the current transaction before doing the updates.
    op.execute("COMMIT")
    op.execute("ALTER TYPE roleenum ADD VALUE IF NOT EXISTS 'approver'")
    op.execute("COMMIT")
    op.execute("UPDATE users SET role = 'approver' WHERE role IN ('reviewer', 'manager')")
    op.execute("COMMIT")
    op.execute("ALTER TYPE documentstatusenum ADD VALUE IF NOT EXISTS 'pending_final_approval'")
    op.execute("COMMIT")
    op.execute("UPDATE documents SET status = 'pending_final_approval' WHERE status IN ('pending_manager_approval', 'pending_finance_approval')")
    op.execute("BEGIN")


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'confidence_score')
    # ### end Alembic commands ###
